kanaverse/kana

public/scran/_inputs.js
public/scran/_qc_filter.js
public/scran/scranWorker.js
src/App.js
src/components/Stats/index.js

This handles one of the points in #28.

Pass dimensions in DATA message, eliminate DIMS special case.

---

public/scran/_inputs.js
public/scran/scranWorker.js
src/components/Analysis/index.js
src/context/AppContext.js

Supports loading previously saved analysis

---

public/scran/_utils_serialize.js
public/scran/scranWorker.js
src/components/Analysis/index.js
src/context/AppContext.js

@LTLA should be ready to test reloading of `.kana` files

Load previously saved analysis

---

src/components/Markers/index.js
src/components/Markers/markers.css
src/components/Plots/QCPlotMgr.js
src/components/Plots/StackedHistogram.js
src/components/Plots/ViolinPlotBasic.js

Aesthetics changes 

---

public/scran/KanaDBHandler.js
public/scran/_inputs.js
public/scran/_normalization.js
public/scran/_tsne_monitor.js
public/scran/_umap_monitor.js
public/scran/_utils.js
public/scran/scranWorker.js
public/scran/tsneWorker.js
src/components/Markers/index.js

Added a store for `file` storage.
Also merged `master`.

Promisify the KanaDB code.

---

public/scran/_inputs.js
src/App.js
src/components/Markers/index.js
src/components/Plots/ImgPlot.js
src/context/AppContext.js

I now pass a dictionary of different namespaces for the genes to the main thread. This needs the corresponding UI change in the marker table to allow choosing between these different namespaces.
This will ultimately enable application of regexes during the QC step.

Store multiple gene names on the worker side.

---

public/scran/KanaDBHandler.js
public/scran/scranWorker.js
src/App.js
src/components/Analysis/index.js
src/components/Header/index.js
src/context/AppContext.js

This guarantees a unique ID, regardless of whatever title the user puts in.

More systematic handling of date, title and IDs for browser saves.

---

src/workers/_tsne_monitor.js
src/workers/_umap_monitor.js
src/workers/scran.worker.js

Shifted worker initialization to the start for simplicity.

Computed UMAP and t-SNEs concurrently with clustering, marker detection.

---

package.json
src/workers/_inputs.js

Depends on jkanche/scran.js#32.

Switch to h5wasm for HDF5 file input.

---

package.json
src/App.css
src/App.js
src/components/Gallery/Gallery.css
src/components/Gallery/index.js
src/components/Header/index.js
src/components/Logs/index.js
src/components/Logs/logs.css
src/workers/scran.worker.js

Pass more messages upon step start, re-use of cached results.

---

package.json
src/App.js
src/components/Analysis/index.js
src/context/AppContext.js
src/workers/scran.worker.js

I believe I have most things setup, but running into CORS errors from bioc azure storage 
we might need someone at bioc to enable cors headers - we need someone at bioc to add cors headers to the azure storage: https://learn.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services

Integrate with ExperimentHub datasets

---

src/components/AnalysisMode/index.js
src/components/NewAnalysis/index.js
src/components/ParamSelection/index.css
src/components/ParamSelection/index.js

restructure params

---

src/components/ExploreMode/index.js
src/components/FeatureSets/index.js
src/components/LoadExplore/H5ADCard.js
src/components/LoadExplore/SECard.js
src/components/LoadExplore/ZippedADBCard.js
src/components/LoadExplore/index.js
src/components/LoadExplore/utils.js
src/components/Markers/index.js
src/components/NewAnalysis/H5ADCard.js
src/components/Plots/DimPlot.js
src/workers/explorer.worker.js
src/workers/scran.worker.js

Cleanups to the explore text

---

package.json
src/components/AnalysisMode/index.js
src/components/ExploreMode/index.js
src/components/FeatureSets/index.js
src/components/Markers/index.js
src/workers/scran.worker.js

Fixes #187, #186, #183, #182, #188

cache, sync and ui bugs 

---

package.json
src/components/AnalysisMode/index.js
src/components/NewAnalysis/ExperimentHubCard.js
src/components/NewAnalysis/H5ADCard.js
src/components/NewAnalysis/MatrixMarketCard.js
src/components/NewAnalysis/RDSSECard.js
src/components/NewAnalysis/TenxHDF5Card.js
src/components/NewAnalysis/utils.js
src/workers/explorer.worker.js
src/workers/helpers.js
src/workers/scran.worker.js

Fix rownames when loading files

---

package.json
src/components/FeatureSets/index.js
src/components/Markers/index.js
src/workers/scran.worker.js

just say `selection {id}` in custom selection dropdown

---

package.json
src/components/FeatureSets/index.js
src/components/Markers/index.js
src/utils/utils.js
src/workers/explorer.worker.js

fix selections in markers and gene set panels (explore mode)

---

package.json
src/App.js
src/components/AnalysisMode/index.js
src/components/ExploreMode/index.js
src/components/NewAnalysis/index.js
src/components/Plots/DimPlot.js
src/utils/utils.js
src/workers/helpers.js

Fix misc issues

---

package.json
src/components/AnalysisMode/index.js
src/components/CellAnnotation/cellanno.css
src/components/CellAnnotation/index.js
src/components/ExploreMode/index.js
src/components/ParamSelection/index.css
src/components/ParamSelection/index.js
src/context/AppContext.js
src/workers/explorer.worker.js
src/workers/helpers.js
src/workers/scran.worker.js
src/workers/translate.js

Begin improving the table for cell type labels.

---

package.json
src/components/AnalysisMode/index.js
src/components/Plots/DimPlot.js
src/components/Plots/colors.js

This switches seamlessly between a hard-coded palette to an algorithmically generated palette at higher numbers.

Switch to some nicer colors based on the scater palette.

---

package.json

fixes nulls in levels from h5ad files
fixes: https://github.com/kanaverse/kana/issues/228

bump bakana version

---

CONTRIBUTING.md

Barely worth fixing, but hopefully still non-zero benefit.

Minor wording tweaks for the Contributing file

---

package.json
src/components/LoadExplore/index.js

fix options issue in explore mode

---

CHANGELOG.md
package.json
src/components/LoadExplore/SECard.js
src/workers/explorer.worker.js

Setting options with RDS files containing pre-computed results
